-- IPL 2026 Player Roster — Updated from official post-auction squads
-- Sources: ESPNcricinfo, iplt20.com, myKhel, Playo
-- base_price in lakhs (200 = ₹2 crore base)

insert into public.ipl_players (name, ipl_team, role, nationality, base_price, is_overseas) values

-- ─────────────── MUMBAI INDIANS (MI) ───────────────
('Rohit Sharma', 'MI', 'batsman', 'India', 200, false),
('Suryakumar Yadav', 'MI', 'batsman', 'India', 200, false),
('Tilak Varma', 'MI', 'batsman', 'India', 200, false),
('Danish Malewar', 'MI', 'batsman', 'India', 200, false),
('Sherfane Rutherford', 'MI', 'batsman', 'West Indies', 200, true),
('Hardik Pandya', 'MI', 'all_rounder', 'India', 200, false),
('Naman Dhir', 'MI', 'all_rounder', 'India', 200, false),
('Raj Angad Bawa', 'MI', 'all_rounder', 'India', 200, false),
('Atharva Ankolekar', 'MI', 'all_rounder', 'India', 200, false),
('Mayank Rawat', 'MI', 'all_rounder', 'India', 200, false),
('Mitchell Santner', 'MI', 'all_rounder', 'New Zealand', 200, true),
('Will Jacks', 'MI', 'all_rounder', 'England', 200, true),
('Corbin Bosch', 'MI', 'all_rounder', 'South Africa', 200, true),
('Quinton de Kock', 'MI', 'wicket_keeper', 'South Africa', 200, true),
('Robin Minz', 'MI', 'wicket_keeper', 'India', 200, false),
('Ryan Rickelton', 'MI', 'wicket_keeper', 'South Africa', 200, true),
('Jasprit Bumrah', 'MI', 'bowler', 'India', 200, false),
('Trent Boult', 'MI', 'bowler', 'New Zealand', 200, true),
('Deepak Chahar', 'MI', 'bowler', 'India', 200, false),
('Shardul Thakur', 'MI', 'bowler', 'India', 200, false),
('Mayank Markande', 'MI', 'bowler', 'India', 200, false),
('Ashwani Kumar', 'MI', 'bowler', 'India', 200, false),
('Mohammad Izhar', 'MI', 'bowler', 'India', 200, false),
('Raghu Sharma', 'MI', 'bowler', 'India', 200, false),
('Allah Ghazanfar', 'MI', 'bowler', 'Afghanistan', 200, true),

-- ─────────────── CHENNAI SUPER KINGS (CSK) ───────────────
('Ruturaj Gaikwad', 'CSK', 'batsman', 'India', 200, false),
('Sarfaraz Khan', 'CSK', 'batsman', 'India', 200, false),
('Ayush Mhatre', 'CSK', 'batsman', 'India', 200, false),
('Dewald Brevis', 'CSK', 'batsman', 'South Africa', 200, true),
('Shivam Dube', 'CSK', 'all_rounder', 'India', 200, false),
('Anshul Kamboj', 'CSK', 'all_rounder', 'India', 200, false),
('Aman Khan', 'CSK', 'all_rounder', 'India', 200, false),
('Prashant Veer', 'CSK', 'all_rounder', 'India', 200, false),
('Ramakrishna Ghosh', 'CSK', 'all_rounder', 'India', 200, false),
('Jamie Overton', 'CSK', 'all_rounder', 'England', 200, true),
('Matthew Short', 'CSK', 'all_rounder', 'Australia', 200, true),
('Zak Foulkes', 'CSK', 'all_rounder', 'England', 200, true),
('Kartik Sharma', 'CSK', 'wicket_keeper', 'India', 200, false),
('MS Dhoni', 'CSK', 'wicket_keeper', 'India', 200, false),
('Sanju Samson', 'CSK', 'wicket_keeper', 'India', 200, false),
('Urvil Patel', 'CSK', 'wicket_keeper', 'India', 200, false),
('Khaleel Ahmed', 'CSK', 'bowler', 'India', 200, false),
('Mukesh Choudhary', 'CSK', 'bowler', 'India', 200, false),
('Rahul Chahar', 'CSK', 'bowler', 'India', 200, false),
('Shreyas Gopal', 'CSK', 'bowler', 'India', 200, false),
('Gurjapneet Singh', 'CSK', 'bowler', 'India', 200, false),
('Noor Ahmad', 'CSK', 'bowler', 'Afghanistan', 200, true),
('Matt Henry', 'CSK', 'bowler', 'New Zealand', 200, true),
('Nathan Ellis', 'CSK', 'bowler', 'Australia', 200, true),
('Akeal Hosein', 'CSK', 'bowler', 'West Indies', 200, true),

-- ─────────────── ROYAL CHALLENGERS BENGALURU (RCB) ───────────────
('Virat Kohli', 'RCB', 'batsman', 'India', 200, false),
('Devdutt Padikkal', 'RCB', 'batsman', 'India', 200, false),
('Rajat Patidar', 'RCB', 'batsman', 'India', 200, false),
('Satvik Deswal', 'RCB', 'batsman', 'India', 200, false),
('Tim David', 'RCB', 'batsman', 'Singapore', 200, true),
('Krunal Pandya', 'RCB', 'all_rounder', 'India', 200, false),
('Venkatesh Iyer', 'RCB', 'all_rounder', 'India', 200, false),
('Vicky Ostwal', 'RCB', 'all_rounder', 'India', 200, false),
('Mangesh Yadav', 'RCB', 'all_rounder', 'India', 200, false),
('Kanishk Chouhan', 'RCB', 'all_rounder', 'India', 200, false),
('Swapnil Singh', 'RCB', 'all_rounder', 'India', 200, false),
('Romario Shepherd', 'RCB', 'all_rounder', 'West Indies', 200, true),
('Jacob Bethell', 'RCB', 'all_rounder', 'England', 200, true),
('Jitesh Sharma', 'RCB', 'wicket_keeper', 'India', 200, false),
('Phil Salt', 'RCB', 'wicket_keeper', 'England', 200, true),
('Jordan Cox', 'RCB', 'wicket_keeper', 'England', 200, true),
('Bhuvneshwar Kumar', 'RCB', 'bowler', 'India', 200, false),
('Yash Dayal', 'RCB', 'bowler', 'India', 200, false),
('Suyash Sharma', 'RCB', 'bowler', 'India', 200, false),
('Rasikh Dar', 'RCB', 'bowler', 'India', 200, false),
('Abhinandan Singh', 'RCB', 'bowler', 'India', 200, false),
('Josh Hazlewood', 'RCB', 'bowler', 'Australia', 200, true),
('Jacob Duffy', 'RCB', 'bowler', 'New Zealand', 200, true),
('Nuwan Thushara', 'RCB', 'bowler', 'Sri Lanka', 200, true),

-- ─────────────── KOLKATA KNIGHT RIDERS (KKR) ───────────────
('Ajinkya Rahane', 'KKR', 'batsman', 'India', 200, false),
('Angkrish Raghuvanshi', 'KKR', 'batsman', 'India', 200, false),
('Manish Pandey', 'KKR', 'batsman', 'India', 200, false),
('Rinku Singh', 'KKR', 'batsman', 'India', 200, false),
('Rahul Tripathi', 'KKR', 'batsman', 'India', 200, false),
('Rovman Powell', 'KKR', 'batsman', 'West Indies', 200, true),
('Cameron Green', 'KKR', 'all_rounder', 'Australia', 200, true),
('Rachin Ravindra', 'KKR', 'all_rounder', 'New Zealand', 200, true),
('Ramandeep Singh', 'KKR', 'all_rounder', 'India', 200, false),
('Anukul Roy', 'KKR', 'all_rounder', 'India', 200, false),
('Sarthak Ranjan', 'KKR', 'all_rounder', 'India', 200, false),
('Daksh Kamra', 'KKR', 'all_rounder', 'India', 200, false),
('Sunil Narine', 'KKR', 'all_rounder', 'West Indies', 200, true),
('Finn Allen', 'KKR', 'wicket_keeper', 'New Zealand', 200, true),
('Tim Seifert', 'KKR', 'wicket_keeper', 'New Zealand', 200, true),
('Tejasvi Dahiya', 'KKR', 'wicket_keeper', 'India', 200, false),
('Varun Chakaravarthy', 'KKR', 'bowler', 'India', 200, false),
('Harshit Rana', 'KKR', 'bowler', 'India', 200, false),
('Kartik Tyagi', 'KKR', 'bowler', 'India', 200, false),
('Vaibhav Arora', 'KKR', 'bowler', 'India', 200, false),
('Akash Deep', 'KKR', 'bowler', 'India', 200, false),
('Umran Malik', 'KKR', 'bowler', 'India', 200, false),
('Matheesha Pathirana', 'KKR', 'bowler', 'Sri Lanka', 200, true),
('Blessing Muzarabani', 'KKR', 'bowler', 'Zimbabwe', 200, true),

-- ─────────────── RAJASTHAN ROYALS (RR) ───────────────
('Yashasvi Jaiswal', 'RR', 'batsman', 'India', 200, false),
('Vaibhav Sooryavanshi', 'RR', 'batsman', 'India', 200, false),
('Shubham Dubey', 'RR', 'batsman', 'India', 200, false),
('Ravi Singh', 'RR', 'batsman', 'India', 200, false),
('Aman Rao Perala', 'RR', 'batsman', 'India', 200, false),
('Shimron Hetmyer', 'RR', 'batsman', 'West Indies', 200, true),
('Ravindra Jadeja', 'RR', 'all_rounder', 'India', 200, false),
('Riyan Parag', 'RR', 'all_rounder', 'India', 200, false),
('Yudhvir Singh Charak', 'RR', 'all_rounder', 'India', 200, false),
('Sam Curran', 'RR', 'all_rounder', 'England', 200, true),
('Dhruv Jurel', 'RR', 'wicket_keeper', 'India', 200, false),
('Donovan Ferreira', 'RR', 'wicket_keeper', 'South Africa', 200, true),
('Lhuan-dre Pretorius', 'RR', 'wicket_keeper', 'South Africa', 200, true),
('Ravi Bishnoi', 'RR', 'bowler', 'India', 200, false),
('Sandeep Sharma', 'RR', 'bowler', 'India', 200, false),
('Tushar Deshpande', 'RR', 'bowler', 'India', 200, false),
('Sushant Mishra', 'RR', 'bowler', 'India', 200, false),
('Kuldeep Sen', 'RR', 'bowler', 'India', 200, false),
('Brijesh Sharma', 'RR', 'bowler', 'India', 200, false),
('Vignesh Puthur', 'RR', 'bowler', 'India', 200, false),
('Yash Raj Punja', 'RR', 'bowler', 'India', 200, false),
('Jofra Archer', 'RR', 'bowler', 'England', 200, true),
('Adam Milne', 'RR', 'bowler', 'New Zealand', 200, true),
('Kwena Maphaka', 'RR', 'bowler', 'South Africa', 200, true),
('Nandre Burger', 'RR', 'bowler', 'South Africa', 200, true),

-- ─────────────── DELHI CAPITALS (DC) ───────────────
('Karun Nair', 'DC', 'batsman', 'India', 200, false),
('Prithvi Shaw', 'DC', 'batsman', 'India', 200, false),
('Sahil Parakh', 'DC', 'batsman', 'India', 200, false),
('Ashutosh Sharma', 'DC', 'batsman', 'India', 200, false),
('Sameer Rizvi', 'DC', 'batsman', 'India', 200, false),
('David Miller', 'DC', 'batsman', 'South Africa', 200, true),
('Pathum Nissanka', 'DC', 'batsman', 'Sri Lanka', 200, true),
('Axar Patel', 'DC', 'all_rounder', 'India', 200, false),
('Nitish Rana', 'DC', 'all_rounder', 'India', 200, false),
('Ajay Mandal', 'DC', 'all_rounder', 'India', 200, false),
('Madhav Tiwari', 'DC', 'all_rounder', 'India', 200, false),
('Tripurana Vijay', 'DC', 'all_rounder', 'India', 200, false),
('Vipraj Nigam', 'DC', 'all_rounder', 'India', 200, false),
('KL Rahul', 'DC', 'wicket_keeper', 'India', 200, false),
('Abhishek Porel', 'DC', 'wicket_keeper', 'India', 200, false),
('Tristan Stubbs', 'DC', 'wicket_keeper', 'South Africa', 200, true),
('Ben Duckett', 'DC', 'wicket_keeper', 'England', 200, true),
('Kuldeep Yadav', 'DC', 'bowler', 'India', 200, false),
('Mukesh Kumar', 'DC', 'bowler', 'India', 200, false),
('T Natarajan', 'DC', 'bowler', 'India', 200, false),
('Mitchell Starc', 'DC', 'bowler', 'Australia', 200, true),
('Kyle Jamieson', 'DC', 'bowler', 'New Zealand', 200, true),
('Lungi Ngidi', 'DC', 'bowler', 'South Africa', 200, true),
('Dushmantha Chameera', 'DC', 'bowler', 'Sri Lanka', 200, true),

-- ─────────────── PUNJAB KINGS (PBKS) ───────────────
('Shreyas Iyer', 'PBKS', 'batsman', 'India', 200, false),
('Nehal Wadhera', 'PBKS', 'batsman', 'India', 200, false),
('Harnoor Singh', 'PBKS', 'batsman', 'India', 200, false),
('Priyansh Arya', 'PBKS', 'batsman', 'India', 200, false),
('Pyla Avinash', 'PBKS', 'batsman', 'India', 200, false),
('Shashank Singh', 'PBKS', 'batsman', 'India', 200, false),
('Musheer Khan', 'PBKS', 'batsman', 'India', 200, false),
('Harpreet Brar', 'PBKS', 'all_rounder', 'India', 200, false),
('Suryansh Shedge', 'PBKS', 'all_rounder', 'India', 200, false),
('Marcus Stoinis', 'PBKS', 'all_rounder', 'Australia', 200, true),
('Marco Jansen', 'PBKS', 'all_rounder', 'South Africa', 200, true),
('Azmatullah Omarzai', 'PBKS', 'all_rounder', 'Afghanistan', 200, true),
('Cooper Connolly', 'PBKS', 'all_rounder', 'Australia', 200, true),
('Mitch Owen', 'PBKS', 'all_rounder', 'Australia', 200, true),
('Prabhsimran Singh', 'PBKS', 'wicket_keeper', 'India', 200, false),
('Vishnu Vinod', 'PBKS', 'wicket_keeper', 'India', 200, false),
('Arshdeep Singh', 'PBKS', 'bowler', 'India', 200, false),
('Yuzvendra Chahal', 'PBKS', 'bowler', 'India', 200, false),
('Vyshak Vijaykumar', 'PBKS', 'bowler', 'India', 200, false),
('Yash Thakur', 'PBKS', 'bowler', 'India', 200, false),
('Praveen Dubey', 'PBKS', 'bowler', 'India', 200, false),
('Vishal Nishad', 'PBKS', 'bowler', 'India', 200, false),
('Lockie Ferguson', 'PBKS', 'bowler', 'New Zealand', 200, true),
('Ben Dwarshuis', 'PBKS', 'bowler', 'Australia', 200, true),
('Xavier Bartlett', 'PBKS', 'bowler', 'Australia', 200, true),

-- ─────────────── SUNRISERS HYDERABAD (SRH) ───────────────
('Abhishek Sharma', 'SRH', 'batsman', 'India', 200, false),
('Smaran Ravichandran', 'SRH', 'batsman', 'India', 200, false),
('Aniket Verma', 'SRH', 'batsman', 'India', 200, false),
('Travis Head', 'SRH', 'batsman', 'Australia', 200, true),
('Nitish Kumar Reddy', 'SRH', 'all_rounder', 'India', 200, false),
('Harshal Patel', 'SRH', 'all_rounder', 'India', 200, false),
('Harsh Dubey', 'SRH', 'all_rounder', 'India', 200, false),
('Shivang Kumar', 'SRH', 'all_rounder', 'India', 200, false),
('Liam Livingstone', 'SRH', 'all_rounder', 'England', 200, true),
('Kamindu Mendis', 'SRH', 'all_rounder', 'Sri Lanka', 200, true),
('Jack Edwards', 'SRH', 'all_rounder', 'Australia', 200, true),
('Brydon Carse', 'SRH', 'all_rounder', 'England', 200, true),
('Ishan Kishan', 'SRH', 'wicket_keeper', 'India', 200, false),
('Salil Arora', 'SRH', 'wicket_keeper', 'India', 200, false),
('Heinrich Klaasen', 'SRH', 'wicket_keeper', 'South Africa', 200, true),
('Jaydev Unadkat', 'SRH', 'bowler', 'India', 200, false),
('Shivam Mavi', 'SRH', 'bowler', 'India', 200, false),
('Zeeshan Ansari', 'SRH', 'bowler', 'India', 200, false),
('Onkar Tarmale', 'SRH', 'bowler', 'India', 200, false),
('Sakib Hussain', 'SRH', 'bowler', 'India', 200, false),
('Praful Hinge', 'SRH', 'bowler', 'India', 200, false),
('Pat Cummins', 'SRH', 'bowler', 'Australia', 200, true),
('Eshan Malinga', 'SRH', 'bowler', 'Sri Lanka', 200, true),
('Amit Kumar', 'SRH', 'bowler', 'India', 200, true),
('Krains Fuletra', 'SRH', 'bowler', 'India', 200, true),

-- ─────────────── LUCKNOW SUPER GIANTS (LSG) ───────────────
('Himmat Singh', 'LSG', 'batsman', 'India', 200, false),
('Ayush Badoni', 'LSG', 'batsman', 'India', 200, false),
('Akshat Raghuwanshi', 'LSG', 'batsman', 'India', 200, false),
('Aiden Markram', 'LSG', 'batsman', 'South Africa', 200, true),
('Matthew Breetzke', 'LSG', 'batsman', 'South Africa', 200, true),
('Abdul Samad', 'LSG', 'all_rounder', 'India', 200, false),
('Shahbaz Ahmed', 'LSG', 'all_rounder', 'India', 200, false),
('Arjun Tendulkar', 'LSG', 'all_rounder', 'India', 200, false),
('Arshin Kulkarni', 'LSG', 'all_rounder', 'India', 200, false),
('Mitchell Marsh', 'LSG', 'all_rounder', 'Australia', 200, true),
('Wanindu Hasaranga', 'LSG', 'all_rounder', 'Sri Lanka', 200, true),
('Rishabh Pant', 'LSG', 'wicket_keeper', 'India', 200, false),
('Mukul Choudhary', 'LSG', 'wicket_keeper', 'India', 200, false),
('Nicholas Pooran', 'LSG', 'wicket_keeper', 'West Indies', 200, true),
('Josh Inglis', 'LSG', 'wicket_keeper', 'Australia', 200, true),
('Mohammed Shami', 'LSG', 'bowler', 'India', 200, false),
('Avesh Khan', 'LSG', 'bowler', 'India', 200, false),
('Mayank Prabhu Yadav', 'LSG', 'bowler', 'India', 200, false),
('Mohsin Khan', 'LSG', 'bowler', 'India', 200, false),
('Digvesh Singh Rathi', 'LSG', 'bowler', 'India', 200, false),
('Akash Maharaj Singh', 'LSG', 'bowler', 'India', 200, false),
('Naman Tiwari', 'LSG', 'bowler', 'India', 200, false),
('M Siddharth', 'LSG', 'bowler', 'India', 200, false),
('Anrich Nortje', 'LSG', 'bowler', 'South Africa', 200, true),
('Prince Yadav', 'LSG', 'bowler', 'India', 200, true),

-- ─────────────── GUJARAT TITANS (GT) ───────────────
('Shubman Gill', 'GT', 'batsman', 'India', 200, false),
('Sai Sudharsan', 'GT', 'batsman', 'India', 200, false),
('M Shahrukh Khan', 'GT', 'batsman', 'India', 200, false),
('Glenn Phillips', 'GT', 'batsman', 'New Zealand', 200, true),
('Nishant Sindhu', 'GT', 'all_rounder', 'India', 200, false),
('Washington Sundar', 'GT', 'all_rounder', 'India', 200, false),
('Jayant Yadav', 'GT', 'all_rounder', 'India', 200, false),
('Rahul Tewatia', 'GT', 'all_rounder', 'India', 200, false),
('R Sai Kishore', 'GT', 'all_rounder', 'India', 200, false),
('Mohd Arshad Khan', 'GT', 'all_rounder', 'India', 200, false),
('Jason Holder', 'GT', 'all_rounder', 'West Indies', 200, true),
('Anuj Rawat', 'GT', 'wicket_keeper', 'India', 200, false),
('Kumar Kushagra', 'GT', 'wicket_keeper', 'India', 200, false),
('Jos Buttler', 'GT', 'wicket_keeper', 'England', 200, true),
('Tom Banton', 'GT', 'wicket_keeper', 'England', 200, true),
('Mohammed Siraj', 'GT', 'bowler', 'India', 200, false),
('Prasidh Krishna', 'GT', 'bowler', 'India', 200, false),
('Kagiso Rabada', 'GT', 'bowler', 'South Africa', 200, true),
('Rashid Khan', 'GT', 'bowler', 'Afghanistan', 200, true),
('Manav Suthar', 'GT', 'bowler', 'India', 200, false),
('Ishant Sharma', 'GT', 'bowler', 'India', 200, false),
('Gurnoor Singh Brar', 'GT', 'bowler', 'India', 200, false),
('Prithvi Raj Yarra', 'GT', 'bowler', 'India', 200, false),
('Luke Wood', 'GT', 'bowler', 'England', 200, true);
('Ashok Sharma', 'GT', 'bowler', 'India', 200, true);
